#!/usr/bin/env python

import subprocess
import sys


def main() -> None:
    argv = list(sys.argv)
    module = argv.pop()
    argv.pop(0)
    args = ['mypy', '--no-check-untyped-defs' ] + argv
    args.append(module)

    ignore_paths = {
        # Ignore errors in other's packages, we don't care
        '/site-packages/',
        'env/src/',
        # No library stub is not our error
        'No library stub',
        'Stub files are',
    }
    print("mypy: checking", module)
    result = subprocess.run(args=args, stdout=subprocess.PIPE)
    result_lines = result.stdout.decode().strip().split('\n')
    error_lines = [
        line for line in result_lines
        if not any(path in line for path in ignore_paths) and line
    ]
    if error_lines:
        print('\n'.join(error_lines))
        sys.exit(1)
    else:
        print("Clean")


if __name__ == '__main__':
    main()
