pipeline:

  lint-daemon:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev gcc linux-headers musl-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beirand/requirements.txt
      - pylint beirand/beirand

  lint-lib:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pylint beiran
  
  lint-cli:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beiran-cli/requirements.txt
      - pylint beiran-cli
  
  publish:
    image: plugins/docker
    dockerfile: beirand/Dockerfile
    repo: reg.rsnc.io/beiran/beiran
    registry: reg.rsnc.io 
    secrets: [ docker_username, docker_password ] 
    tags:
      - latest
      - 1.0.1
      - 1.0 

  notify-rsnc:
    group: notify
    image: plugins/slack
    channel: beiran
    username: drone
    webhook: https://chat.rsnc.io/hooks/jhw1tcrpbpnybez4a3db16i1rw
    icon_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]
  
  notify-cl-slack:
    group: notify
    image: plugins/slack
    channel: beiran_pj
    username: drone
    webhook: https://hooks.slack.com/services/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
    icon_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]