services:
  docker:
    image: docker


pipeline:
  pre-build:
    group: build
    image: docker
    repo: dkr.rsnc.io/poc/beiran/beiran
    environment:
      - DOCKER_HOST=unix:///var/run/host.sock
    commands:
      - docker build --cache-from dkr.rsnc.io/poc/beiran/beiran:edge -t dkr.rsnc.io/poc/beiran/beiran:drone-build-${DRONE_BUILD_NUMBER} .
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro

  pylint-build:
    group: build
    image: docker
    environment:
      - DOCKER_HOST=unix:///var/run/host.sock
    commands:
      - docker build -t dkr.rsnc.io/poc/beiran/pylint -f docker-pylint/Dockerfile .
      - docker push dkr.rsnc.io/poc/beiran/pylint
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro

  lint-daemon:
    image: dkr.rsnc.io/poc/beiran/pylint
    group: lint
    commands:
      - pylint beirand/beirand

  lint-lib:
    image: dkr.rsnc.io/poc/beiran/pylint
    group: lint
    commands:
      - pylint beiran
  
  lint-cli:
    image: dkr.rsnc.io/poc/beiran/pylint
    group: lint
    commands:
      - pylint beiran_cli
  
  beirand:
    image: dkr.rsnc.io/poc/beiran/beiran:drone-build-${DRONE_BUILD_NUMBER}
    detach: true
    environment:
      - DISCOVERY_METHOD=dns
      - DISCOVERY_SERVICE_ADDRESS=beirand
      - LOG_LEVEL=INFO
      - DOCKER_HOST=http://127.0.0.1:2375
      - LISTEN_ADDR=0.0.0.0
    commands:
      - date
      - ip addr show
      - python3 /src/beirand/main.py
  
  rest_test:
    image: python:3-jessie
    environment:
      - LOG=True
      - LOG_LEVEL=DEBUG
      - PRINT_BODIES=True
    commands: 
      - date
      - ip addr show
      - ss -aut || netstat -anp || cat /proc/net/tcp || echo "nothing supported for listing ports :/"
      - pip install pycurl pyresttest
      - pyresttest --url http://beirand:8888 --test test/rest_api/beirand.yaml --print-bodies=True --print-headers=True --log=debug

  publish:
    image: docker
    environment:
      - DOCKER_HOST=unix:///var/run/host.sock
    commands:
      - "export DOCKER_HOST=unix:///var/run/host.sock"
      - docker tag dkr.rsnc.io/poc/beiran/beiran:done-build-${DRONE_BUILD_NUMBER} dkr.rsnc.io/poc/beiran/beiran:egde
      - docker push dkr.rsnc.io/poc/beiran/beiran:egde
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro


  notify-rsnc:
    group: notify
    image: plugins/slack
    channel: beiran
    username: drone
    webhook: https://chat.rsnc.io/hooks/jhw1tcrpbpnybez4a3db16i1rw
    icon_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    when:
      status: [ success, failure ]

  notify-cl-slack:
    group: notify
    image: plugins/slack
    channel: beiran_pj
    username: Drone
    webhook: https://hooks.slack.com/services/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
    icon_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    when:
      status: [ success, failure ]
