service:
  docker:
    image: docker
  beirand: 
    image: dkr.rlab.io/poc/beiran/daemon
    privileged: true
    command: python3.6 -u beirand/main.py
    environment:
      - DISCOVERY_METHOD=dns
      - DISCOVERY_SERVICE_ADDRESS=beirand
      - LOG_LEVEL=INFO
      - DOCKER_HOST=http://127.0.0.1:2375

pipeline:
  lint-daemon:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev gcc linux-headers musl-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beirand/requirements.txt
      - pylint beirand/beirand

  lint-lib:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pylint beiran
  
  lint-cli:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beiran-cli/requirements.txt
      - pylint beiran-cli
  
  rest_test:
    image: python:3-jessie
    environment:
      - LOG=True
      - LOG_LEVEL=DEBUG
      - PRINT_BODIES=True
    commands: 
      - pip install pycurl pyresttest
      - pyresttest --url http://127.0.0.1:8888 --test test/rest_api/beirand.yaml --print-bodies=True --print-headers=True --log=debug


  publish:
    image: plugins/docker
    dockerfile: beirand/Dockerfile
    repo: reg.rsnc.io/beiran/beiran
    registry: reg.rsnc.io 
    secrets: [ docker_username, docker_password ] 
    tags:
      - latest
      - 1.0.1
      - 1.0 

  notify:
    image: plugins/slack
    channel: beiran
    username: drone
    webhook: https://chat.rsnc.io/hooks/jhw1tcrpbpnybez4a3db16i1rw
    when:
      status: [ success, failure ]
  
