services:
  registry:
    image: registry
  docker:
    image: docker


pipeline:
  pre-build:
    image: plugins/docker
    cache_from: dkr.rsnc.io/poc/beiran/beiran:latest
    repo: registry:5000/beiran
    insecure: registry:5000
    tags:
      - drone-build-${DRONE_BUILD_NUMBER}

  lint-daemon:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev gcc linux-headers musl-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beirand/requirements.txt
      - pylint beirand/beirand

  lint-lib:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pylint beiran
  
  lint-cli:
    image: clburlison/pylint
    group: lint
    commands:
      - apk add --update --no-cache python-dev
      - pip install -r beiran/requirements.txt
      - pip install -r beiran_cli/requirements.txt
      - pylint beiran_cli
  
  beirand:
    image: registry:5000/beiran:drone-build-${DRONE_BUILD_NUMBER}
    detach: true
    environment:
      - DISCOVERY_METHOD=dns
      - DISCOVERY_SERVICE_ADDRESS=beirand
      - LOG_LEVEL=INFO
      - DOCKER_HOST=http://127.0.0.1:2375
      - LISTEN_ADDR=0.0.0.0
    commands:
      - date
      - ip addr show
      - python3 /src/beirand/main.py
  
  rest_test:
    image: python:3-jessie
    environment:
      - LOG=True
      - LOG_LEVEL=DEBUG
      - PRINT_BODIES=True
    commands: 
      - date
      - ip addr show
      - ss -aut || netstat -anp || cat /proc/net/tcp || echo "nothing supported for listing ports :/"
      - pip install pycurl pyresttest
      - pyresttest --url http://beirand:8888 --test test/rest_api/beirand.yaml --print-bodies=True --print-headers=True --log=debug

  publish:
    image: plugins/docker
    dry_run: true
    cache_from: dkr.rsnc.io/poc/beiran/beiran
    repo: dkr.rsnc.io/poc/beiran/beiran
    tags:
      - drone-build-${DRONE_BUILD_NUMBER}
      - edge

  notify:
    image: plugins/slack
    channel: beiran
    username: drone
    webhook: https://chat.rsnc.io/hooks/jhw1tcrpbpnybez4a3db16i1rw
    when:
      status: [ success, failure ]
