
stages:
 - test_image
 - lint
 - test

test_image:
 stage: test_image
 tags:
  - docker
 script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  - docker pull dkr.rlab.io/poc/beiran/test:latest || true
  - ./make.sh push_test_image

lint:lib:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pylint beiran

lint:daemon:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pylint beirand/beirand

lint:cli:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pylint beiran-cli

test:
 stage: test
 tags:
  - docker
 script:
  - ./make test_using_docker
