stages:
 - pre_build
 - checks
 - start_test_services
 - test
 # - publish
 - cleanup

pre_build:daemon:
  stage: pre_build
  tags:
   - docker
  script:
   - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:latest || true
   - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
   - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME,$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:ci-${CI_PIPELINE_ID} -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
   - docker push $CI_REGISTRY_IMAGE:ci-${CI_PIPELINE_ID}
   - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}

pre_build:checker:
  stage: pre_build
  tags:
   - docker
  script:
   - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE/checks:latest || true
   - docker build --cache-from $CI_REGISTRY_IMAGE/checks:latest -t $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID} -t $CI_REGISTRY_IMAGE/checks:latest -f helpers/docker/checks/Dockerfile .
   - docker push $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
   - docker push $CI_REGISTRY_IMAGE/checks:latest

checks:lint-daemon:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - pylint beirand

checks:lint-client:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - pylint beiran

checks:lint-plugins:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - pylint plugins

checks:bandit-daemon:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - bandit -r beirand
  allow_failure: true

checks:bandit-client:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - bandit -r beiran
  allow_failure: true

checks:bandit-plugins:
  stage: checks
  image: $CI_REGISTRY_IMAGE/checks:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - bandit -r plugins
  allow_failure: true

start_test_services:
  stage: start_test_services
  tags:
   - docker
  script:
   - SRC_DIR=$(pwd)
   - mkdir -p /tmp/beirantest-${CI_PIPELINE_ID}
   - cd /tmp/beirantest-${CI_PIPELINE_ID}
   - cp $SRC_DIR/docker-compose.multipod.yml ./docker-compose.yml
   - sed -i "s/dkr\.rsnc\.io\/poc\/beiran\/daemon:dev/$CI_REGISTRY_IMAGE:ci-${CI_PIPELINE_ID}/g" docker-compose.yml
   - docker-compose up -d pod1 docker1 pod2 docker2 pod3 docker3
   - sleep 5
   # seed docker daemon (docker1 only)
   - docker-compose exec -T docker1 docker pull hello-world
   - docker-compose exec -T docker1 docker pull alpine:latest
   - docker-compose exec -T docker1 docker images
   # starting beiran
   - docker-compose up -d beiran1

test:unit:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci-${CI_PIPELINE_ID}
  tags:
   - docker
  script:
   - pytest

test:api:
  stage: test
  tags:
   - docker
  script:
   - cd /tmp/beirantest-${CI_PIPELINE_ID}
   - |
     echo "waiting until beirand is accessible"
     times=0
     until $(docker-compose exec -T beirand1 curl --output /dev/null --silent --fail http://beirand1:8888); do
         printf '.'
         sleep 3
         times=$(( $times + 1 ))
         if [ $times -eq 10 ]; then
           2>&1 echo "timed out waiting for beirand"
           exit 1
         fi
     done
   - docker-compose exec -T beirand1 pyresttest --url http://beirand1:8888 --test test/rest_api/beirand.yaml

cleanup:services:
  stage: cleanup
  tags:
   - docker
  when: always
  script:
   - cd /tmp/beirantest-${CI_PIPELINE_ID}
   - docker-compose kill || true
   - docker-compose rm -f
   - cd /
   - rm -rf /tmp/beirantest-${CI_PIPELINE_ID}

# cleanup:
#   image: alpine:3.7
#   FIXME: volumes is not supported by gitlab-ci yet
#   volumes:
#    - /tmp/beiran-build-vols:/tmp/beiran-build-vols
#   commands:
#    - echo "Cleaning up docker storage"
#    - export B_DIR=/tmp/beiran-build-vols/dockerd1-${CI_PIPELINE_ID} 
#    - if [ ! -d $B_DIR ]; then exit 0; fi
#    - du -ch -d1 $B_DIR
#    - rm -rf $B_DIR
#   when: always
