
stages:
 - lint
 - test

lint:lib:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pytest beiran

lint:daemon:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pytest beirand/beirand

lint:cli:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pytest beiran-cli

test:
 stage: test
 image: python:3
 tags:
  - docker
 script:
  - pip3 install pytest
  - pytest
