
stages:
 - lint
 - test

lint:
 stage: lint
 image: dkr.rlab.io/poc/beiran/test:latest
 tags:
  - docker
 script:
  - pytest beiran
  - pytest beirand/beirand
  - pytest beiran-cli

test:
 stage: test
 image: python:3
 tags:
  - docker
 script:
  - pip3 install pytest
  - pytest
