# This docker-compose is for development environment
version: '2'
services:
  beiran1:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    command: python3.6 -u beirand/main.py
    environment:
      - DISCOVERY_METHOD=zeroconf
      - LISTEN_ADDR=0.0.0.0
      - LISTEN_PORT=8889
      - LOG_LEVEL=INFO

  beiran2:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    command: python3.6 -u beirand/main.py
    environment:
      - DISCOVERY_METHOD=zeroconf
      - LISTEN_ADDR=0.0.0.0
      - LOG_LEVEL=INFO
      - LISTEN_PORT=8890

  beiran3:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    command: python3.6 -u beirand/main.py
    environment:
      - DISCOVERY_METHOD=zeroconf
      - LISTEN_ADDR=0.0.0.0
      - LOG_LEVEL=INFO
      - LISTEN_PORT=8891
