# This docker-compose is for dns discovery test environment
version: '2'
services:
  beiran_dns:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    networks:
      - test
    volumes:
     - .:/src
    environment:
      - BEIRAN_DISCOVERY_METHOD=dns
      - BEIRAN_DISCOVERY_DNS_CONFIG='discovery_service_address=beiran_dns'
      - BEIRAN_LISTEN_ADDR=0.0.0.0
      - BEIRAN_LOG_LEVEL=INFO

networks:
  test:
