# This docker-compose is for development environment
version: '2'
services:
  beirand:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker:/var/lib/docker
     - ./beiran:/opt/beiran/beiran:ro
     - ./beiran_cli:/opt/beiran/beiran_cli:ro
     - ./plugins:/opt/beiran/plugins:ro
     - /etc/beiran
    network_mode: host
    environment:
      - BEIRAN_DISCOVERY_METHOD=zeroconf
      - BEIRAN_LISTEN_ADDRESS=0.0.0.0
      - BEIRAN_DISCOVERY_DNS_CONFIG='discovery_service_address=beirand'
      - BEIRAN_LOG_LEVEL=INFO
