# This docker-compose is for development environment
version: '2'
services:
  beiran1:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    environment:
      - BEIRAN_DISCOVERY_METHOD=zeroconf
      - BEIRAN_LISTEN_ADDR=0.0.0.0
      - BEIRAN_LISTEN_PORT=8889
      - BEIRAN_LOG_LEVEL=INFO

  beiran2:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    environment:
      - BEIRAN_DISCOVERY_METHOD=zeroconf
      - BEIRAN_LISTEN_ADDR=0.0.0.0
      - BEIRAN_LOG_LEVEL=INFO
      - BEIRAN_LISTEN_PORT=8890

  beiran3:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    network_mode: host
    volumes:
     - .:/src
    environment:
      - BEIRAN_DISCOVERY_METHOD=zeroconf
      - BEIRAN_LISTEN_ADDR=0.0.0.0
      - BEIRAN_LOG_LEVEL=INFO
      - BEIRAN_LISTEN_PORT=8891
