# This docker-compose is for dns discovery test environment
version: '2'
services:
  beiran_dns:
    image: dkr.rsnc.io/poc/beiran/daemon:dev
    build: .
    networks:
      - test
    volumes:
     - .:/src
    command: python3.6 -u beirand/main.py
    environment:
      - DISCOVERY_METHOD=dns
      - DISCOVERY_SERVICE_ADDRESS=beiran_dns
      - LISTEN_ADDR=0.0.0.0
      - LOG_LEVEL=INFO

networks:
  test:
