version: '2'
services:
  beirand:
    image: rlab.io/beiran
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - test
    command: python3.6 -u beiran.py
networks:
  test:
