# beiran configuration file

# general settings which is valid all parts, lib, daemon and all plugins
[beiran]
log_level = 'DEBUG'
log_file = 'beirand.log'
config_dir = '.'
data_dir = '.'
listen_port = 8888
socket_path = 'beirand.sock'
daemon_url = ''

# docker plugin settings
[package.docker]
enabled = true
cache_dir = '.'

# dns discovery settings
[discovery.dns]
enabled = true

# zeroconf discovery settings
[discovery.zeroconf]
enabled = true
