# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='descriptor.proto',
  package='containerd.types',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x64\x65scriptor.proto\x12\x10\x63ontainerd.types\x1a\x14gogoproto/gogo.proto\"r\n\nDescriptor\x12\x12\n\nmedia_type\x18\x01 \x01(\t\x12\x42\n\x06\x64igest\x18\x02 \x01(\tB2\xda\xde\x1f*github.com/opencontainers/go-digest.Digest\xc8\xde\x1f\x00\x12\x0c\n\x04size\x18\x03 \x01(\x03\x42\x32Z0github.com/containerd/containerd/api/types;typesX\x00\x62\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_DESCRIPTOR = _descriptor.Descriptor(
  name='Descriptor',
  full_name='containerd.types.Descriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_type', full_name='containerd.types.Descriptor.media_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digest', full_name='containerd.types.Descriptor.digest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037*github.com/opencontainers/go-digest.Digest\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='containerd.types.Descriptor.size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['Descriptor'] = _DESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Descriptor = _reflection.GeneratedProtocolMessageType('Descriptor', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTOR,
  __module__ = 'descriptor_pb2'
  # @@protoc_insertion_point(class_scope:containerd.types.Descriptor)
  ))
_sym_db.RegisterMessage(Descriptor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z0github.com/containerd/containerd/api/types;types'))
_DESCRIPTOR.fields_by_name['digest'].has_options = True
_DESCRIPTOR.fields_by_name['digest']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037*github.com/opencontainers/go-digest.Digest\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
